# Dependencies
markdown: redcarpet
highlighter: pygments

excerpt_separator: "<!--more-->"

# Permalinks
permalink: /:title
timezone: Asia/Hong_Kong

# Setup
title: 花溪乡网(www.huaxixiang.com)
description: '花溪乡网(www.huaxixiang.com)的 Github 同步更新站.'
baseurl:     ''
url:         'http://www.huaxixiang.com'

gems:
  - jekyll-sitemap

author:
  name: 'Eagle'
  url: http://www.huaxixiang.com
  email: greatwqs@163.com

paginate: 8

# Custom vars
show_related_posts: true

google_analytics: UA-23350797-1
comments: true